### ISSUE TITLE
Desenvolver algoritmo para módulo RFID 125KHz - RDM6300 para Arduino

### ISSUE THREAD

**Issue by felipeduarte34** [UIoT/uiot_execution_layer#10]
Desenvolver código para homologação do módulo RFId 125 KHz

**Comment by tomsqueiroz** [comment]
O módulo RFID 125KHz já foi homologado. O código já se encontra no git hub: (https://github.com/UIoT/middleware_sc_execl/tree/master/execl_use_cases_codes/new_codes/arduino/rfid_reader).
