### ISSUE TITLE
Desenvolver algoritmo para Slave Controller (Raspbery PI) para comunicação TCP/IP

### ISSUE THREAD

**Issue by felipeduarte34** [UIoT/uiot_execution_layer#15]

**Comment by Bunoviske** [comment]
A comunicação entre os dispositivos já foi realizada, sendo o Slave servidor e o Arduino cliente. Falta concluir os testes invertendo os papeis.
Código do TCP server (Raspberry):https://github.com/UIoT/middleware_sc_execl/blob/ExemplosSocketEmC/execl_use_cases_codes/new_codes/others/tcpserver.c
