### ISSUE TITLE
Desenvolver algoritmo para microcontrolador Arduino com módulo WiFi - ESP8266

### ISSUE THREAD

**Issue by felipeduarte34** [UIoT/uiot_execution_layer#5]
Realizar integração com modulo o modulo WiFi ESP8266.

Testar comunicação entre do Arduino TCP IP através do modulo WiFi.

**Teste 1**
       Esta comunicação se dará entre um Arduino com o modulo ESP8266 e com um Raspberry PI 2. O Raspberry Pi será o servidor e microcontrolador o Cliente.

**Teste 2**
       Esta comunicação se dará entre um Arduino com o modulo ESP8266 e com um RaspBerry PI  2. Sendo o Arduino o servidor e o Raspberry Pi será o cliente.

**Comment by tomsqueiroz** [comment]
Tiraram o código de servidor TCP do git, eu envio de novo pra poder citar no comentário de finalização de tarefa ou só cito mesmo ?

**Comment by tomsqueiroz** [comment]
O teste 1 já foi realizado. Utilizamos o módulo ESP8266 como cliente TCP para se conectar ao Raspberry Pi 2 que rodava  ArchLinux. O código utilizado para o arduino se encontra no GitHub: middleware_sc_execl/execl_use_cases_codes/new_codes/arduino/esp8266_tcp_client. O principal problema foi a não-estabilidade do ESP8266 devido a um erro no circuito. O erro foi resolvido alterando um divisor de corrente que possuía 1 resistor de 20kOhm e 1 resistor de 10kOhm, que baixava a tensão para um valor muito próximo da exigida pelo módulo e dificultava a comunicação entre o Arduino Uno e o ESP8266. A alteração consistiu em trocar o resistor de 20kOhm por outro de 10kOhm, o que implicou em uma tensão mais adequada para o circuito.

**Comment by Bunoviske** [comment]
Código em do esp8266 para comandos AT em andamento. Ele foi dividido em três módulos seguindo orientação a objeto: conexão (manipula as ações de conexão do esp), dados (manipulação dos dados) e comando AT (envia comandos AT pela UART). Está sendo desenvolvido um gerador de comandos seguindo um protocolo e esse código trata o esp como um TCP/UDP client no modo STATION. Para tratá-lo como ACESS POINT tem que alterar o código. Deixarei essa parte para depois, quando for necessário implementar no projeto.
