### ISSUE TITLE
Desenvolver algoritmo para microcontrolador Arduino com módulo Bluetooth - HC-05

### ISSUE THREAD

**Issue by felipeduarte34** [UIoT/uiot_execution_layer#6]
Realizar integração com os módulos bluetooth HC-05.

Testar comunicação entre Arduinos. 

Comunicando um Arduino com o outro através dos módulos HC-05, cada Arduino possuirá um módulo HC-05 estabelecendo a comunicação Full duplex entre eles.

**Comment by Bunoviske** [comment]
O pareamento entre dois dispositivos bluetooth já foi realizado, mas ainda é preciso testar o envio de dados. Para o modulo entrar em modo de configuração por meio de comandos at, é necessário seguir as etapas a seguir:
-ligue o arduino e retire o jumper de alimentação do modulo bluetooth
-segure o botão do modulo, e enquanto faz isso, ligue o modulo conectando
o jumper responsável pela alimentação.
-após ligar, basta soltar o botão e ele estará em modo de configuração

Lembra-se que o pareamento sempre deve ser feito entre um master e um slave.
Código:middleware_sc_execl/execl_use_cases_codes/new_codes/arduino/bluetooth-HC05/at_commands.ino

**Comment by Bunoviske** [comment]
Troca de dados concluída. 

Código para o master:  middleware_sc_execl/execl_use_cases_codes/new_codes/arduino/bluetooth-HC05/master_senddata.ino 

Código para o slave:  middleware_sc_execl/execl_use_cases_codes/new_codes/arduino/bluetooth-HC05/slave_receivedata.ino
