### ISSUE TITLE
Desenvolver algoritmo para microcontrolador Arduino com modulos RF 433MHz

### ISSUE THREAD

**Issue by felipeduarte34** [UIoT/uiot_execution_layer#7]
Realizar integração com os módulos de comunicação RX e TX 433MHz.

Testar comunicação entre Arduinos. 

**Teste 1**
Comunicando um Arduino com o outro através dos modulos, em um Arduino ficará um modulo de transmissão e no segundo modulo ficará o modulo de recepçao.

**Teste 2**
Comunicando um Arduino com outro Arduino, ambos com modulo TX e RX. Ou seja, neste teste será implementado uma comunicação Half-Duplex, sendo os Micontroladores enviando e recebendo dados.

**Comment by Bunoviske** [comment]
Primeira parte da tarefa concluída. A comunicação entre dois arduinos foi realizada e a troca de dados também. Falta implementar a comunicação half-duplex. 
Código:  https://github.com/UIoT/middleware_sc_execl/tree/master/execl_use_cases_codes/new_codes/arduino/433MHZ
