### ISSUE TITLE
Desenvolver algoritmo para microcontrolador Arduino com módulo Ethernet baseado no chip W5100

### ISSUE THREAD

**Issue by felipeduarte34** [UIoT/uiot_execution_layer#8]
Realizar integração com modulo o modulo Ethernet.

Testar comunicação entre do Arduino TCP IP através do modulo Ethernet.

**Teste 1**
       Esta comunicação se dará entre um Arduino com o modulo Ethernet e com um Raspberry PI 2. O Raspberry Pi será o servidor e microcontrolador o Cliente.

**Teste 2**
       Esta comunicação se dará entre um Arduino com o modulo Ethernet e com um RaspBerry PI  2. Sendo o Arduino o servidor e o Raspberry Pi será o cliente.

**Comment by tomsqueiroz** [comment]
O teste 1 já foi realizado e o código do cliente que utilizamos no arduino já se encontra no GitHub
[https://github.com/UIoT/middleware_sc_execl/tree/master/execl_use_cases_codes/new_codes/arduino/ethernet_shield]. O código utilizado no RaspBerryPI 2 é genérico para servidores TCP e também se encontra no GitHub [https://github.com/UIoT/middleware_sc_execl/blob/ExemplosSocketEmC/execl_use_cases_codes/new_codes/others/tcpserver.c].
